server.port=8085

spring.datasource.url=jdbc:h2:mem:cvdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

api-key-auth.keys[0].key=app-cv
api-key-auth.keys[0].hash=fa59024eb2a1c5b5ba897926f9776d6796237a4d5f6d82664c1f224faceb5ab9
